const talks: Talk[] = [
  {
    title: 'The day I reverse engineered a furry Gameboy Advance game',
    date: '2021-08-14',
    language: 'English',
    eventName: 'DEFCON Furs 2021',
    videoLink: 'https://www.youtube.com/watch?v=RMM_5bq3Ct8',
    slidesLink: 'https://speakerdeck.com/macabeus/the-day-i-reverse-engineered-a-furry-gameboy-advance-game',
    eventLink: 'https://2021.dcfurs.com/',
    previously: [
      {
        name: 'The Conf 2019',
        link: 'https://www.youtube.com/watch?v=X88pmwSltAY',
      },
      {
        name: 'BalCCon2k19',
        link: 'https://www.youtube.com/watch?v=xh0V1jRVnQI',
      },
    ],
    tags: ['Reverse Engineering'],
  },
  {
    title: 'A linguagem Fluent - Sistema de localização para as traduções fluírem naturalmente',
    date: '2020-08-20',
    language: 'Portuguese',
    eventName: 'AngularSP #30',
    videoLink: 'https://www.youtube.com/watch?v=nJnAVUIyf5U',
    slidesLink: 'https://speakerdeck.com/macabeus/a-linguagem-fluent-sistema-de-localizacao-para-as-traducoes-fluirem-naturalmente',
    eventLink: 'https://www.meetup.com/pt-BR/AngularJS-Sao-Paulo/events/272391707/',
    tags: ['Localization'],
  },
  {
    title: 'Aprendendo compiladores fazendo um',
    date: '2018-07-16',
    language: 'Portuguese',
    eventName: 'Pagar.me Talks',
    videoLink: 'https://www.youtube.com/watch?v=t77ThZNCJGY',
    slidesLink: 'https://speakerdeck.com/macabeus/aprendendo-compiladores-fazendo-um-parte-1',
    eventLink: 'https://www.youtube.com/c/PagarmeTalks',
    tags: ['Compilers', 'Elixir'],
  },
  {
    title: 'Demystifying compilers by writing your own',
    date: '2018-11-14',
    language: 'English',
    eventName: 'The Conf 2018',
    videoLink: 'https://www.youtube.com/watch?v=zMJYoYwOCd4',
    slidesLink: 'https://speakerdeck.com/macabeus/demystifying-compilers-by-writing-your-own',
    eventLink: 'https://2018.theconf.club/',
    tags: ['Compilers', 'Elixir'],
  },
  {
    title: 'Arquitetura de Event Sourcing Usando Elixir',
    date: '2018-11-14',
    language: 'Portuguese',
    eventName: 'Nerdzão #37 - Back-End',
    videoLink: 'https://www.youtube.com/watch?v=tixWGkkZbXE',
    slidesLink: 'https://speakerdeck.com/macabeus/event-sourcing-architecture-using-elixir',
    eventLink: 'https://www.meetup.com/pt-BR/Nerdzao/events/248323275',
    tags: ['Architecture', 'Elixir'],
  },
  {
    title: 'GraphQL & iOS',
    date: '2017-11-23',
    language: 'Portuguese',
    eventName: '12º CocoaHeads Fortaleza',
    videoLink: 'https://youtu.be/oomQ-FXKA84',
    slidesLink: 'https://speakerdeck.com/macabeus/graphql-plus-ios',
    eventLink: 'https://web.archive.org/web/20190119180006/https://www.cocoaheads.com.br/agendas/detalhes/215',
    tags: ['GraphQL', 'Swift', 'iOS'],
  },
]

export default talks
